[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = "0.35.1"
shuttle-runtime = "0.35.1"
shuttle-secrets = "0.35.1"
tracing = "0.1.37"
tokio = "1.26.0"
